name: Test app action

on:
  pull_request:
    branches:
      - master

jobs:
  Metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.1'
      - name: Install Dependencies
        run: npm install && npm build

      - name: Install surge
        run: npm install --save-dev surge && surge

      # - name: Surge deploy
      #   run: npm surge
        # run: surge build/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}


#     strategy:
#       matrix:
#         node-version: [8.x, 10.x, 12.x]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm install
#     - run: npm run build --if-present
#     - run: npm test
#       env:
#         CI: true
