name: Test app action

on:
  pull_request:
    branches:
      - master

jobs:
  Metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.1'
      - name: Install Dependencies
        run: npm install
      
      - name: run build
        run: npm run-script build

      - name: Install surge
        run: npm install -g surge

      - name: Surge deploy
        run: surge build/ test-my-domain.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Performance instalation
        run: npm i puppeteer && npm install lighthouse && npm install @actions/core && npm install @actions/github && npm install node-fetch

      - name: performance
        env:
          secret: ${{ secrets.GIT_TOKEN }}
          surgeUrl: http://test-my-domain.surge.sh
        run: node ./.github/workflows/scripts/performance.js


#     strategy:
#       matrix:
#         node-version: [8.x, 10.x, 12.x]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm install
#     - run: npm run build --if-present
#     - run: npm test
#       env:
#         CI: true
